Register variable which can be used later in a playbook to test if ru…
jtyr/ansible-udev_rename_netiface pull request #1
Opened 2017-01-29 22:35 UTC by haad

…les where changed.

2017-01-29 23:21 UTC, jtyr commented
Thanks for your PR, @haad. Please could you explain for what exactly you want to use the variable later in the playbook?

2017-01-30 07:55 UTC, haad commented
To be able to detect a change. In which case i have to reboot server to
apply new settings.

On Jan 30, 2017 12:21 AM, "Jiri Tyr" <notifications@github.com> wrote:

> Thanks for your PR, @haad <https://github.com/haad>. Please could you
> explain for what exactly you want to use the variable later in the playbook?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jtyr/ansible-udev_rename_netiface/pull/1#issuecomment-275954863>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEIzslAJr0ywpQ9PSHSvJtT_oH1GwTRks5rXR71gaJpZM4Lw7xd>
> .
>

2017-01-30 11:50 UTC, jtyr requested changes

2017-01-30 11:50 UTC, jtyr commented on tasks/main.yaml
> +  register: udev_rename_netiface
Please rename the variable to `udev_rename_netiface_config_changed`.

2017-01-30 13:41 UTC, haad commented on tasks/main.yaml
> +  register: udev_rename_netiface
Should be ok now

2017-01-30 13:42 UTC, jtyr approved these changes

2017-01-30 13:52 UTC, jtyr commented
Merged. Thanks for your PR.

2017-01-30 13:52 UTC, closed without merging